version: "3"
services:
  nginx:
    build:
      context: "./services/Nginx"
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "80:80"
  db:
    build:
      context: "./services/DB"
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=SP
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
  backend:
    build:
      context: "./services/Backend"
      dockerfile: Dockerfile.dev
    environment:
      - BACKEND_CLIENT_PORT=3030
      - DATABASE_URL=mongodb://root:password@db:27017/SP
    depends_on:
      - db
  willowglen:
    build:
      context: "./services/Willowglen"
      dockerfile: Dockerfile.dev
    environment:
      WILLOWGLEN_CLIENT_PORT: 3031
