const alerts = require("./alerts/alerts.service.js");
const stations = require("./stations/stations.service.js");
const device = require("./device/device.service.js");
const floorplan2d = require("./floorplan2d/floorplan2d.service.js");
const alarms = require("./alarms/alarms.service.js");
const reports = require("./reports/reports.service.js");
const floorplan3d = require(".//floorplan3d/floorplan3d.service.js");
const personnel = require("./personnel/personnel.service.js");
const reportsType = require("./reports-type/reports-type.service.js");
const departments = require("./departments/departments.service.js");
const statusType = require("./status-type/status-type.service.js");
const cctvFeed = require("./cctv-feed/cctv-feed.service.js");
const cctvVisitors = require("./cctv-visitors/cctv-visitors.service.js");
const geoInfo = require("./geo-info/geo-info.service.js");
const floorplanDevices = require("./floorplan-devices/floorplan-devices.service.js");
const floorplanDevicesModel = require("./floorplan-devices-model/floorplan-devices-model.service.js");
const pointType = require("./point-type/point-type.service.js");
const eventsLog = require("./events-log/events-log.service.js");
const rules = require("./rules/rules.service.js");
const dashboardControl = require('./dashboard-control/dashboard-control.service.js');
const audio = require('./audio/audio.service.js');
const bacsLog = require('./bacs-log/bacs-log.service.js');
const bacsLogType = require('./bacs-log-type/bacs-log-type.service.js');
const patrolLog = require('./patrol-log/patrol-log.service.js');
const systemType = require('./system-type/system-type.service.js');
const cctvTemplate = require('./cctv-template/cctv-template.service.js');
const dashboardTemplate = require('./dashboard-template/dashboard-template.service.js');
const config = require('./config/config.service.js');
const pinTemplate = require('./pin-template/pin-template.service.js');
const actionMessage = require('./action-message/action-message.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(alerts);
  app.configure(stations);
  app.configure(device);
  app.configure(floorplan2d);
  app.configure(alarms);
  app.configure(reports);
  app.configure(floorplan3d);
  app.configure(personnel);
  app.configure(reportsType);
  app.configure(departments);
  app.configure(statusType);
  app.configure(cctvFeed);
  app.configure(cctvVisitors);
  app.configure(geoInfo);
  app.configure(floorplanDevices);
  app.configure(floorplanDevicesModel);
  app.configure(pointType);
  app.configure(eventsLog);
  app.configure(rules);
  app.configure(dashboardControl);
  app.configure(audio);
  app.configure(bacsLog);
  app.configure(bacsLogType);
  app.configure(patrolLog);
  app.configure(systemType);
  app.configure(cctvTemplate);
  app.configure(dashboardTemplate);
  app.configure(config);
  app.configure(pinTemplate);
  app.configure(actionMessage);
};
